/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bus_Book;

/**
 *
 * @author viraj
 */
public class Bookings_2 extends javax.swing.JFrame {

    /**
     * Creates new form Bookings_2
     */
    public Bookings_2() {
        initComponents();
    }
    
    public Bookings_2(String Name,String Phone, String Name1,String Phone1) {
        initComponents();
        name_con_1.setText(Name);
        phone_con_1.setText(Phone);
        name_con_1.setVisible(false);
        phone_con_1.setVisible(false);
    }
    
    public Bookings_2(String Name1,String Phone1) {
        initComponents();
        name_con_1.setText(Name1);
        phone_con_1.setText(Phone1);
        name_con_1.setVisible(false);
        phone_con_1.setVisible(false);
    }
    /*
    public Bookings_2(String Phone_1) {
        initComponents();
        phone_con_1.setText(Phone_1);
        phone_con_1.setVisible(false);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bookings_BG_Panel = new javax.swing.JPanel();
        Bookings_Panel_1 = new javax.swing.JPanel();
        Select_Booking_Lab = new javax.swing.JLabel();
        Go_TO_Private = new javax.swing.JButton();
        Go_To_Seat_ = new javax.swing.JButton();
        Back_sep = new javax.swing.JButton();
        name_con_1 = new javax.swing.JLabel();
        phone_con_1 = new javax.swing.JLabel();
        Bookings_Lab_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bookings_BG_Panel.setBackground(new java.awt.Color(102, 102, 102));

        Bookings_Panel_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Select_Booking_Lab.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        Select_Booking_Lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Select_Booking_Lab.setText(".. Select Your Bookings ..");
        Bookings_Panel_1.add(Select_Booking_Lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 13, 515, 70));

        Go_TO_Private.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Go_TO_Private.setForeground(new java.awt.Color(255, 255, 255));
        Go_TO_Private.setText("Private Bus");
        Go_TO_Private.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        Go_TO_Private.setContentAreaFilled(false);
        Go_TO_Private.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go_TO_PrivateActionPerformed(evt);
            }
        });
        Bookings_Panel_1.add(Go_TO_Private, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 200, 60));

        Go_To_Seat_.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Go_To_Seat_.setForeground(new java.awt.Color(255, 255, 255));
        Go_To_Seat_.setText("Regular Seat");
        Go_To_Seat_.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        Go_To_Seat_.setContentAreaFilled(false);
        Go_To_Seat_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go_To_Seat_ActionPerformed(evt);
            }
        });
        Bookings_Panel_1.add(Go_To_Seat_, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 200, 60));

        Back_sep.setBackground(new java.awt.Color(255, 255, 255));
        Back_sep.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Back_sep.setForeground(new java.awt.Color(255, 255, 255));
        Back_sep.setText("Back");
        Back_sep.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        Back_sep.setContentAreaFilled(false);
        Back_sep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_sepActionPerformed(evt);
            }
        });
        Bookings_Panel_1.add(Back_sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 200, 60));
        Bookings_Panel_1.add(name_con_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 50));
        Bookings_Panel_1.add(phone_con_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 50));

        Bookings_Lab_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_Pictures/old-yellow-vintage-bus-on-the-foggy-prairie-road-wall-mural_1.jpg"))); // NOI18N
        Bookings_Panel_1.add(Bookings_Lab_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 610));

        javax.swing.GroupLayout Bookings_BG_PanelLayout = new javax.swing.GroupLayout(Bookings_BG_Panel);
        Bookings_BG_Panel.setLayout(Bookings_BG_PanelLayout);
        Bookings_BG_PanelLayout.setHorizontalGroup(
            Bookings_BG_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bookings_BG_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bookings_Panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Bookings_BG_PanelLayout.setVerticalGroup(
            Bookings_BG_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bookings_BG_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bookings_Panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bookings_BG_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bookings_BG_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Go_TO_PrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go_TO_PrivateActionPerformed
        // TODO add your handling code here:
        
        
        String Name=name_con_1.getText();
        String Phone=phone_con_1.getText();
        new Detail_1(Name,Phone).setVisible(true);
        setVisible(false);                     //Connection
        
    }//GEN-LAST:event_Go_TO_PrivateActionPerformed

    private void Back_sepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_sepActionPerformed
        // TODO add your handling code here:
        dispose();
         
    }//GEN-LAST:event_Back_sepActionPerformed

    private void Go_To_Seat_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go_To_Seat_ActionPerformed
        // TODO add your handling code here:
        dispose();
        String Name1=name_con_1.getText();
        String Phone1=phone_con_1.getText();
        new publicbus(Name1,Phone1).setVisible(true);
        setVisible(false);
        
//        publicbus j=new publicbus();
//        j.setVisible(true);
    }//GEN-LAST:event_Go_To_Seat_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookings_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookings_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookings_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookings_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookings_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_sep;
    private javax.swing.JPanel Bookings_BG_Panel;
    private javax.swing.JLabel Bookings_Lab_BG;
    private javax.swing.JPanel Bookings_Panel_1;
    private javax.swing.JButton Go_TO_Private;
    private javax.swing.JButton Go_To_Seat_;
    private javax.swing.JLabel Select_Booking_Lab;
    public javax.swing.JLabel name_con_1;
    public javax.swing.JLabel phone_con_1;
    // End of variables declaration//GEN-END:variables
}
