/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bus_Book;

/**
 *
 * @author VIRAJ
 */
public class lastpage extends javax.swing.JFrame {

    /**
     * Creates new form lastpage
     */
    public lastpage() {
        initComponents();
    }
    
    public lastpage(String Name,String Phone, String from, String to, String type, String seats){
        initComponents();
        Name_Lab_Display.setText(Name);
        Phone_Lab_Display.setText(Phone);
        from_last.setText(from);
        to_last.setText(to);
        ac_Lab.setText(type);
        Num_seats.setText(seats);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Final_Exit_Button = new javax.swing.JButton();
        Name_Lab_Display = new javax.swing.JLabel();
        from_last = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        to_last = new javax.swing.JLabel();
        Phone_Lab_Display = new javax.swing.JLabel();
        ac_Lab = new javax.swing.JLabel();
        Num_seats = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("! Your Booking is Confirmed !");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 450, 70));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thanks For Choosing Us ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 490, 80));

        Final_Exit_Button.setBackground(new java.awt.Color(51, 51, 255));
        Final_Exit_Button.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
        Final_Exit_Button.setText("HAPPY JOURNEY");
        Final_Exit_Button.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        Final_Exit_Button.setContentAreaFilled(false);
        Final_Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Final_Exit_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Final_Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 450, 80));

        Name_Lab_Display.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Name_Lab_Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Name_Lab_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 220, 42));

        from_last.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        from_last.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(from_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 212, 150, 50));

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("To");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 293, 150, 50));

        to_last.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        to_last.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(to_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 381, 150, 50));

        Phone_Lab_Display.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Phone_Lab_Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Phone_Lab_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 230, 42));

        ac_Lab.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        ac_Lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(ac_Lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 170, 50));

        Num_seats.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Num_seats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Num_seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 170, 50));

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 160, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_Pictures/b12.gif"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 166, 590, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Final_Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Final_Exit_ButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Welcom_Form u=new Welcom_Form();
        u.setVisible(true);
    }//GEN-LAST:event_Final_Exit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lastpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lastpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lastpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lastpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lastpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Final_Exit_Button;
    public javax.swing.JLabel Name_Lab_Display;
    private javax.swing.JLabel Num_seats;
    public javax.swing.JLabel Phone_Lab_Display;
    private javax.swing.JLabel ac_Lab;
    private javax.swing.JLabel from_last;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel to_last;
    // End of variables declaration//GEN-END:variables
}
