/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bus_Book;

import javax.swing.JOptionPane;

/**
 *
 * @author VIRAJ
 */
public class privatebus extends javax.swing.JFrame {

    /**
     * Creates new form colorpage
     */
    public privatebus() {
        initComponents();
        
    }

   public privatebus(String Name,String Phone) {
        initComponents();
        Name_Lab_Sec.setText(Name);
        Phone_Lab_Sec.setText(Phone);
        Name_Lab_Sec.setVisible(false);
        Phone_Lab_Sec.setVisible(false);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bus_Seat_Number = new javax.swing.JComboBox<>();
        Non_AC_Button = new javax.swing.JRadioButton();
        AC_Button = new javax.swing.JRadioButton();
        Depart_dest = new javax.swing.JComboBox<>();
        Arrive_Dest = new javax.swing.JComboBox<>();
        Search_Button = new javax.swing.JButton();
        Back_TO_Button = new javax.swing.JButton();
        Cancel_11 = new javax.swing.JButton();
        Departure_Label = new javax.swing.JLabel();
        Arrival_Label = new javax.swing.JLabel();
        Seat_Select_Lab = new javax.swing.JLabel();
        Date_Choose_Depart = new com.toedter.calendar.JDateChooser();
        date_Choose_Arrive = new com.toedter.calendar.JDateChooser();
        Name_Lab_Sec = new javax.swing.JLabel();
        Phone_Lab_Sec = new javax.swing.JLabel();
        Extra_Lab_Sec = new javax.swing.JLabel();
        Private_Lab_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bus_Seat_Number.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Bus_Seat_Number.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "20", "35", "50" }));
        Bus_Seat_Number.setOpaque(false);
        getContentPane().add(Bus_Seat_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 132, 34));

        Non_AC_Button.setBackground(new java.awt.Color(153, 255, 255));
        Non_AC_Button.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Non_AC_Button.setText("NON AC");
        Non_AC_Button.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        Non_AC_Button.setBorderPainted(true);
        Non_AC_Button.setOpaque(false);
        Non_AC_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Non_AC_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Non_AC_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 150, -1));

        AC_Button.setBackground(new java.awt.Color(153, 255, 255));
        AC_Button.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        AC_Button.setText("AC");
        AC_Button.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        AC_Button.setBorderPainted(true);
        AC_Button.setOpaque(false);
        AC_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AC_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 100, -1));

        Depart_dest.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Depart_dest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dadar", "Borivali", "Vasai", "Worli", "Bhayander" }));
        Depart_dest.setOpaque(false);
        getContentPane().add(Depart_dest, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 190, -1));

        Arrive_Dest.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Arrive_Dest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mahabaleshwar", "Raigad Fort", "Matheran", "Lonavala", "Ellora Caves" }));
        Arrive_Dest.setOpaque(false);
        getContentPane().add(Arrive_Dest, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 190, -1));

        Search_Button.setBackground(new java.awt.Color(153, 255, 255));
        Search_Button.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Search_Button.setForeground(new java.awt.Color(51, 102, 255));
        Search_Button.setText("SEARCH BUS");
        Search_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Search_Button.setContentAreaFilled(false);
        Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Search_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 250, 70));

        Back_TO_Button.setBackground(new java.awt.Color(153, 255, 255));
        Back_TO_Button.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Back_TO_Button.setForeground(new java.awt.Color(51, 102, 255));
        Back_TO_Button.setText("BACK");
        Back_TO_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back_TO_Button.setContentAreaFilled(false);
        Back_TO_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_TO_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Back_TO_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 120, 60));

        Cancel_11.setBackground(new java.awt.Color(153, 255, 255));
        Cancel_11.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Cancel_11.setForeground(new java.awt.Color(0, 51, 255));
        Cancel_11.setText("CANCEL");
        Cancel_11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cancel_11.setContentAreaFilled(false);
        Cancel_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_11ActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 160, 70));

        Departure_Label.setBackground(new java.awt.Color(153, 255, 255));
        Departure_Label.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Departure_Label.setText("DEPARTURE :");
        getContentPane().add(Departure_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 113, -1, 46));

        Arrival_Label.setBackground(new java.awt.Color(153, 255, 255));
        Arrival_Label.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Arrival_Label.setText("ARRIVAL :");
        getContentPane().add(Arrival_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 218, -1, 46));

        Seat_Select_Lab.setBackground(new java.awt.Color(153, 255, 255));
        Seat_Select_Lab.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Seat_Select_Lab.setText("SELECT TOTAL SEATS\n");
        getContentPane().add(Seat_Select_Lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 39));

        Date_Choose_Depart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Date_Choose_DepartFocusLost(evt);
            }
        });
        getContentPane().add(Date_Choose_Depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 163, 36));

        date_Choose_Arrive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                date_Choose_ArriveKeyReleased(evt);
            }
        });
        getContentPane().add(date_Choose_Arrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 163, 36));
        getContentPane().add(Name_Lab_Sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 120, 50));
        getContentPane().add(Phone_Lab_Sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 120, 50));
        getContentPane().add(Extra_Lab_Sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 120, 50));

        Private_Lab_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_Pictures/b4.gif"))); // NOI18N
        Private_Lab_BG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(Private_Lab_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cancel_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_11ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Cancel_11ActionPerformed

    private void Non_AC_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Non_AC_ButtonActionPerformed
        // TODO add your handling code here:
        if(Non_AC_Button.isSelected()){
            AC_Button.setSelected(false);
        }
    }//GEN-LAST:event_Non_AC_ButtonActionPerformed

    private void Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ButtonActionPerformed
        // TODO add your handling code here:
        String FrP, TooP, Num_L;
        FrP = (String)Depart_dest.getSelectedItem();
        TooP = (String)Arrive_Dest.getSelectedItem();
        //Num_L = (String)Num_Display_Lab.getText();
        String Dept = "";
        Dept = Date_Choose_Depart.toString();
        String Arrive= "";
        Arrive =date_Choose_Arrive.toString();
        
        if(FrP == "Select" || TooP == "Select"){
            JOptionPane.showMessageDialog(null,"!! Select Trip !!");
        }

        else {    
       dispose();
        String Name=Name_Lab_Sec.getText();
        String Phone=Phone_Lab_Sec.getText();
        String from1 = "";
        from1 = Depart_dest.getSelectedItem().toString();
        String arrival1 = "";
        arrival1 = Arrive_Dest.getSelectedItem().toString();
        String Date2 = Date_Choose_Depart.getDateFormatString();
        String Date3 = date_Choose_Arrive.getDateFormatString();
        String Seat2 = "";
        Seat2 = Bus_Seat_Number.getSelectedItem().toString();
        String Condn = "";
        if(AC_Button.isSelected())
        {
            Condn=AC_Button.getText();
        }
        else if(Non_AC_Button.isSelected())
        {
            Condn=Non_AC_Button.getText();
        }
        new privatebusbook(Name,Phone,from1,arrival1,Date2,Date3,Seat2,Condn).setVisible(true);
        }
        
    }//GEN-LAST:event_Search_ButtonActionPerformed

    private void Back_TO_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_TO_ButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        
        String Name=Name_Lab_Sec.getText();
        String Phone=Phone_Lab_Sec.getText();
        new Detail_1(Name,Phone).setVisible(true);
            
        
//        Detail_1 m=new Detail_1();
//        m.setVisible(true);
    }//GEN-LAST:event_Back_TO_ButtonActionPerformed

    private void AC_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC_ButtonActionPerformed
        // TODO add your handling code here:
        if(AC_Button.isSelected()){
            Non_AC_Button.setSelected(false);
        }
    }//GEN-LAST:event_AC_ButtonActionPerformed

    private void date_Choose_ArriveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date_Choose_ArriveKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_date_Choose_ArriveKeyReleased

    private void Date_Choose_DepartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Date_Choose_DepartFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Date_Choose_DepartFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(privatebus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(privatebus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(privatebus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(privatebus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new privatebus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AC_Button;
    private javax.swing.JLabel Arrival_Label;
    private javax.swing.JComboBox<String> Arrive_Dest;
    private javax.swing.JButton Back_TO_Button;
    private javax.swing.JComboBox<String> Bus_Seat_Number;
    private javax.swing.JButton Cancel_11;
    private com.toedter.calendar.JDateChooser Date_Choose_Depart;
    private javax.swing.JComboBox<String> Depart_dest;
    private javax.swing.JLabel Departure_Label;
    public javax.swing.JLabel Extra_Lab_Sec;
    public javax.swing.JLabel Name_Lab_Sec;
    private javax.swing.JRadioButton Non_AC_Button;
    public javax.swing.JLabel Phone_Lab_Sec;
    private javax.swing.JLabel Private_Lab_BG;
    private javax.swing.JButton Search_Button;
    private javax.swing.JLabel Seat_Select_Lab;
    private com.toedter.calendar.JDateChooser date_Choose_Arrive;
    // End of variables declaration//GEN-END:variables
}
