/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bus_Book;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author VIRAJ
 */
public class publicbusbook extends javax.swing.JFrame {

    
    DefaultTableModel model=null;
    /**
     * Creates new form publicbusbook
     */
    public publicbusbook() {
        initComponents();
    }
    
    public publicbusbook(String Name1,String Phone1,String from,String arrival,String Date1,String Seat1,String Condn1) {
        initComponents();
        Name_Lab_Sec_2.setText(Name1);
        Phone_Lab_Sec_2.setText(Phone1);
        Name_Lab_Sec_2.setVisible(true);
        Phone_Lab_Sec_2.setVisible(true);
        publicbusbook_from.setText(from);
        publicbusbook_arrival.setText(arrival);
        Number_Of_Seats_Val_1.setText(Seat1);
        AC_Non_Lab_2.setText(Condn1);
        
        pub_ac.setText(Condn1);
        pub_ac.setVisible(false);
        pub_from.setText(from);
        pub_from.setVisible(false);
        pub_to.setText(arrival);
        pub_to.setVisible(false);
        addition.setText(Seat1);
        addition.setVisible(false);
    }
    
    public void setTable1(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_booking_system","root","");
            PreparedStatement pst= con.prepareStatement("select * from publicbusbook_detail");
            ResultSet rst = pst.executeQuery();
            
            while (rst.next()){
                
                String Bus_Num= rst.getString("Bus_Num_1");
                String From_Dest= rst.getString("From_Dest_1");
                String To_Dest= rst.getString("To_Dest_1");
                String Type_Bus= rst.getString("Type_Bus_1");
                
                Object[] obj = {Bus_Num,From_Dest,To_Dest,Type_Bus};
                
                model = (DefaultTableModel) Publicbusbook_Table.getModel();
                model.addRow(obj);
                
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }
    
    public void Search1(String str){
        model = (DefaultTableModel) Publicbusbook_Table.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<> (model);  //Search filter code
        Publicbusbook_Table.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        publicbusbook_Mid_pan = new javax.swing.JPanel();
        publicbusbook_fare = new javax.swing.JLabel();
        Next_To_Public = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Publicbusbook_Table = new javax.swing.JTable();
        show_fare_1 = new javax.swing.JButton();
        publicbusbook_from = new javax.swing.JLabel();
        num_Seats = new javax.swing.JLabel();
        Number_Of_Seats_Val_1 = new javax.swing.JLabel();
        _to_ = new javax.swing.JLabel();
        publicbusbook_arrival = new javax.swing.JLabel();
        AC_Non_Lab_2 = new javax.swing.JLabel();
        publicbusbook_back = new javax.swing.JButton();
        pub_from = new javax.swing.JLabel();
        pub_ac = new javax.swing.JLabel();
        pub_to = new javax.swing.JLabel();
        addition = new javax.swing.JLabel();
        Name_Lab_Sec_2 = new javax.swing.JLabel();
        Phone_Lab_Sec_2 = new javax.swing.JLabel();
        Extra_Lab_Sec_2 = new javax.swing.JLabel();
        PublicBusbook_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        publicbusbook_Mid_pan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        publicbusbook_Mid_pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        publicbusbook_fare.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        publicbusbook_fare.setForeground(new java.awt.Color(255, 255, 255));
        publicbusbook_Mid_pan.add(publicbusbook_fare, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 150, 50));

        Next_To_Public.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        Next_To_Public.setForeground(new java.awt.Color(255, 255, 255));
        Next_To_Public.setText("Next");
        Next_To_Public.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        Next_To_Public.setContentAreaFilled(false);
        Next_To_Public.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_To_PublicActionPerformed(evt);
            }
        });
        publicbusbook_Mid_pan.add(Next_To_Public, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 200, 50));

        Publicbusbook_Table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Publicbusbook_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus No.", "From", "To", "Type"
            }
        ));
        jScrollPane1.setViewportView(Publicbusbook_Table);

        publicbusbook_Mid_pan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 660, 190));

        show_fare_1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        show_fare_1.setForeground(new java.awt.Color(255, 255, 255));
        show_fare_1.setText("Show Fare :");
        show_fare_1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        show_fare_1.setContentAreaFilled(false);
        show_fare_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_fare_1ActionPerformed(evt);
            }
        });
        publicbusbook_Mid_pan.add(show_fare_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 200, 50));

        publicbusbook_from.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        publicbusbook_from.setForeground(new java.awt.Color(255, 255, 255));
        publicbusbook_from.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        publicbusbook_Mid_pan.add(publicbusbook_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 190, 60));

        num_Seats.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        num_Seats.setForeground(new java.awt.Color(255, 255, 255));
        num_Seats.setText("Number of Seats :");
        publicbusbook_Mid_pan.add(num_Seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 180, 60));

        Number_Of_Seats_Val_1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Number_Of_Seats_Val_1.setForeground(new java.awt.Color(255, 255, 255));
        Number_Of_Seats_Val_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        publicbusbook_Mid_pan.add(Number_Of_Seats_Val_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 130, 60));

        _to_.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        _to_.setForeground(new java.awt.Color(255, 255, 255));
        _to_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _to_.setText("To");
        publicbusbook_Mid_pan.add(_to_, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 109, 30, 60));

        publicbusbook_arrival.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        publicbusbook_arrival.setForeground(new java.awt.Color(255, 255, 255));
        publicbusbook_arrival.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        publicbusbook_Mid_pan.add(publicbusbook_arrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 190, 60));

        AC_Non_Lab_2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        AC_Non_Lab_2.setForeground(new java.awt.Color(255, 255, 255));
        AC_Non_Lab_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        publicbusbook_Mid_pan.add(AC_Non_Lab_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 130, 60));

        publicbusbook_back.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        publicbusbook_back.setForeground(new java.awt.Color(255, 255, 255));
        publicbusbook_back.setText("BACK");
        publicbusbook_back.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        publicbusbook_back.setContentAreaFilled(false);
        publicbusbook_back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        publicbusbook_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicbusbook_backActionPerformed(evt);
            }
        });
        publicbusbook_Mid_pan.add(publicbusbook_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 60));
        publicbusbook_Mid_pan.add(pub_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 30));
        publicbusbook_Mid_pan.add(pub_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 30));
        publicbusbook_Mid_pan.add(pub_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 30));
        publicbusbook_Mid_pan.add(addition, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 30));

        Name_Lab_Sec_2.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Name_Lab_Sec_2.setForeground(new java.awt.Color(255, 255, 255));
        publicbusbook_Mid_pan.add(Name_Lab_Sec_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 110, 60));

        Phone_Lab_Sec_2.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Phone_Lab_Sec_2.setForeground(new java.awt.Color(255, 255, 255));
        publicbusbook_Mid_pan.add(Phone_Lab_Sec_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 190, 60));
        publicbusbook_Mid_pan.add(Extra_Lab_Sec_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 120, 60));

        PublicBusbook_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_Pictures/Book_BG2.jpeg"))); // NOI18N
        PublicBusbook_BG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        publicbusbook_Mid_pan.add(PublicBusbook_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 580));

        getContentPane().add(publicbusbook_Mid_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void publicbusbook_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicbusbook_backActionPerformed
        // TODO add your handling code here:
        dispose();
        String Name1=Name_Lab_Sec_2.getText();
        String Phone1=Phone_Lab_Sec_2.getText();
        new publicbus(Name1,Phone1).setVisible(true);
        setVisible(false);
        
//        publicbus o=new publicbus();
//        o.setVisible(true);
    }//GEN-LAST:event_publicbusbook_backActionPerformed

    private void Next_To_PublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_To_PublicActionPerformed
        // TODO add your handling code here:
        dispose();
        String Name1=Name_Lab_Sec_2.getText();
        String Phone1=Phone_Lab_Sec_2.getText();
        String from = pub_from.getText();
        String arrival = pub_to.getText();
        String Condn1 = pub_ac.getText();
        String Seat1 = addition.getText();
        new paynew(Name1, Phone1, from, arrival, Condn1, Seat1).setVisible(true);
        setVisible(false);
//        paynew aa=new paynew();
//        aa.setVisible(true);
    }//GEN-LAST:event_Next_To_PublicActionPerformed

    private void show_fare_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_fare_1ActionPerformed
        // TODO add your handling code here:
        setTable1();
        
        String i,j,k,ac1;
        ac1=(AC_Non_Lab_2.getText());
        k=(Number_Of_Seats_Val_1.getText());
        i= (publicbusbook_from.getText());
        j = (publicbusbook_arrival.getText());
        Search1(ac1);
        Search1(k);
        Search1(i);
        Search1(j);
       if(ac1=="NON-AC"){
        if(i=="Morewadi Chowk" && j=="Dadar"){
            int z=400;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Morewadi Chowk" && j=="Satara"){
            int z=120;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Morewadi Chowk" && j=="Pune"){
            int z=190;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Morewadi Chowk" && j=="Worli"){
            int z=70;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Morewadi Chowk" && j=="Bhayander"){
            int z=160;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Limb Phata" && j=="Dadar"){
            int z=300;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Limb Phata" && j=="Satara"){
            int z=90;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Limb Phata" && j=="Pune"){
            int z=170;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Limb Phata" && j=="Worli"){
            int z=100;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Limb Phata" && j=="Bhayander"){
            int z=195;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Vasai parnaka" && j=="Dadar"){
            int z=150;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Vasai parnaka" && j=="Satara"){
            int z=250;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Vasai parnaka" && j=="Pune"){
            int z=310;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Vasai parnaka" && j=="Worli"){
            int z=80;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Vasai parnaka" && j=="Bhayander"){
            int z=35;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="borivali bustop" && j=="Dadar"){
            int z=50;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="borivali bustop" && j=="Satara"){
            int z=180;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="borivali bustop" && j=="Pune"){
            int z=220;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="borivali bustop" && j=="Worli"){
            int z=30;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="borivali bustop" && j=="Bhayander"){
            int z=25;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Sion Bustop" && j=="Dadar"){
            int z=80;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Sion Bustop" && j=="Satara"){
            int z=200;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Sion Bustop" && j=="Pune"){
            int z=240;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Sion Bustop" && j=="Worli"){
            int z=20;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Sion Bustop" && j=="Bhayander"){
            int z=65;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
       }
       else if(ac1=="AC"){
           if(i=="Morewadi Chowk" && j=="Dadar"){
            int z=500;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Morewadi Chowk" && j=="Satara"){
            int z=220;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Morewadi Chowk" && j=="Pune"){
            int z=290;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Morewadi Chowk" && j=="Worli"){
            int z=170;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Morewadi Chowk" && j=="Bhayander"){
            int z=260;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Limb Phata" && j=="Dadar"){
            int z=400;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Limb Phata" && j=="Satara"){
            int z=190;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Limb Phata" && j=="Pune"){
            int z=270;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Limb Phata" && j=="Worli"){
            int z=200;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Limb Phata" && j=="Bhayander"){
            int z=295;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Vasai parnaka" && j=="Dadar"){
            int z=250;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Vasai parnaka" && j=="Satara"){
            int z=350;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Vasai parnaka" && j=="Pune"){
            int z=410;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Vasai parnaka" && j=="Worli"){
            int z=180;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Vasai parnaka" && j=="Bhayander"){
            int z=135;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="borivali bustop" && j=="Dadar"){
            int z=150;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="borivali bustop" && j=="Satara"){
            int z=280;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="borivali bustop" && j=="Pune"){
            int z=320;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="borivali bustop" && j=="Worli"){
            int z=130;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="borivali bustop" && j=="Bhayander"){
            int z=125;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Sion Bustop" && j=="Dadar"){
            int z=180;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Sion Bustop" && j=="Satara"){
            int z=300;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Sion Bustop" && j=="Pune"){
            int z=340;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Sion Bustop" && j=="Worli"){
            int z=120;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
        else if(i=="Sion Bustop" && j=="Bhayander"){
            int z=165;
            int n = Integer.parseInt(k);
            int mult=n*z;
            String g=Integer.toString(mult);
            publicbusbook_fare.setText(g);
        }
       }
    }//GEN-LAST:event_show_fare_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(publicbusbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(publicbusbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(publicbusbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(publicbusbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new publicbusbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AC_Non_Lab_2;
    private javax.swing.JLabel Extra_Lab_Sec_2;
    private javax.swing.JLabel Name_Lab_Sec_2;
    private javax.swing.JButton Next_To_Public;
    private javax.swing.JLabel Number_Of_Seats_Val_1;
    private javax.swing.JLabel Phone_Lab_Sec_2;
    private javax.swing.JLabel PublicBusbook_BG;
    private javax.swing.JTable Publicbusbook_Table;
    private javax.swing.JLabel _to_;
    private javax.swing.JLabel addition;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel num_Seats;
    private javax.swing.JLabel pub_ac;
    private javax.swing.JLabel pub_from;
    private javax.swing.JLabel pub_to;
    private javax.swing.JPanel publicbusbook_Mid_pan;
    private javax.swing.JLabel publicbusbook_arrival;
    private javax.swing.JButton publicbusbook_back;
    private javax.swing.JLabel publicbusbook_fare;
    private javax.swing.JLabel publicbusbook_from;
    private javax.swing.JButton show_fare_1;
    // End of variables declaration//GEN-END:variables
}
