package Bus_Book;
import java.awt.Dimension;
import java.util.regex.*;
import javax.swing.JPasswordField;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author viraj
 */
public class Registration_Form extends javax.swing.JFrame {

    /**
     * Creates new form Registration_Form
     */
    public Registration_Form() {
        initComponents();
    }
    
    Connection connection= null;

    
    public void uniqueName(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_booking_system","root","");
            Statement stat = con.createStatement();
            String st = N_Field_1.getText();
            String selectQuery = "SELECT COUNT(*) from registration_form where Name_Reg = '"+st+"'";
            ResultSet rs = stat.executeQuery(selectQuery) ;
            rs.next();
            String Countrow = rs.getString(1);
            if(Countrow.equals("1")){
                JOptionPane.showMessageDialog(null,"! Name is Taken !");
                N_Field_1.setText("");
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void uniquePass(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_booking_system","root","");
            Statement stat = con.createStatement();
            String st = Pass_Field_1.getText();
            String selectQuery = "SELECT COUNT(*) from registration_form where Password_Reg = '"+st+"'";
            ResultSet rs = stat.executeQuery(selectQuery) ;
            rs.next();
            String Countrow = rs.getString(1);
            if(Countrow.equals("1")){
                JOptionPane.showMessageDialog(null,"! Password is Taken !");
                Pass_Field_1.setText("");
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registrion_B_Panel = new javax.swing.JPanel();
        Registration_Panel = new javax.swing.JPanel();
        N_Field_1 = new javax.swing.JTextField();
        Email_Lab_Reg = new javax.swing.JLabel();
        E_Field = new javax.swing.JTextField();
        Phone_Lab_Reg = new javax.swing.JLabel();
        Ph_Field = new javax.swing.JTextField();
        Pass_Lab_Reg = new javax.swing.JLabel();
        Pass_Field_1 = new javax.swing.JPasswordField();
        Name_Lab_Reg = new javax.swing.JLabel();
        N_Warn = new javax.swing.JLabel();
        E_Warn = new javax.swing.JLabel();
        Ph_Warn = new javax.swing.JLabel();
        Pass_Warn = new javax.swing.JLabel();
        Age_Lab_Reg = new javax.swing.JLabel();
        Age_Field = new javax.swing.JTextField();
        Gender_Lab_Reg = new javax.swing.JLabel();
        Gender_Combo_Reg = new javax.swing.JComboBox<>();
        Registration_Button = new javax.swing.JButton();
        Cancel_Button_1 = new javax.swing.JButton();
        Age_Warn = new javax.swing.JLabel();
        Back_Button_1 = new javax.swing.JButton();
        Register_Lab = new javax.swing.JLabel();
        Show_Pass_Check = new javax.swing.JCheckBox();
        Registration_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Registrion_B_Panel.setBackground(new java.awt.Color(51, 51, 51));
        Registrion_B_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registration_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Registration_Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Registration_Panel.setForeground(new java.awt.Color(255, 255, 255));
        Registration_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        N_Field_1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        N_Field_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        N_Field_1.setDragEnabled(true);
        N_Field_1.setSelectionColor(new java.awt.Color(153, 153, 153));
        N_Field_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                N_Field_1FocusLost(evt);
            }
        });
        N_Field_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_Field_1ActionPerformed(evt);
            }
        });
        N_Field_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                N_Field_1KeyReleased(evt);
            }
        });
        Registration_Panel.add(N_Field_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 487, 55));

        Email_Lab_Reg.setBackground(new java.awt.Color(255, 255, 255));
        Email_Lab_Reg.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Email_Lab_Reg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Email_Lab_Reg.setText("Email :");
        Registration_Panel.add(Email_Lab_Reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 107, 50));

        E_Field.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        E_Field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        E_Field.setDragEnabled(true);
        E_Field.setSelectionColor(new java.awt.Color(153, 153, 153));
        E_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                E_FieldKeyReleased(evt);
            }
        });
        Registration_Panel.add(E_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 487, 55));

        Phone_Lab_Reg.setBackground(new java.awt.Color(255, 255, 255));
        Phone_Lab_Reg.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Phone_Lab_Reg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Phone_Lab_Reg.setText("Phone :");
        Registration_Panel.add(Phone_Lab_Reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 107, 55));

        Ph_Field.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Ph_Field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        Ph_Field.setDragEnabled(true);
        Ph_Field.setSelectionColor(new java.awt.Color(153, 153, 153));
        Ph_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ph_FieldActionPerformed(evt);
            }
        });
        Ph_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Ph_FieldKeyReleased(evt);
            }
        });
        Registration_Panel.add(Ph_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 487, 55));

        Pass_Lab_Reg.setBackground(new java.awt.Color(255, 255, 255));
        Pass_Lab_Reg.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Pass_Lab_Reg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Pass_Lab_Reg.setText("Password :");
        Registration_Panel.add(Pass_Lab_Reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 107, 55));

        Pass_Field_1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Pass_Field_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        Pass_Field_1.setDragEnabled(true);
        Pass_Field_1.setSelectionColor(new java.awt.Color(153, 153, 153));
        Pass_Field_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Pass_Field_1FocusLost(evt);
            }
        });
        Pass_Field_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Pass_Field_1KeyReleased(evt);
            }
        });
        Registration_Panel.add(Pass_Field_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 487, 55));

        Name_Lab_Reg.setBackground(new java.awt.Color(255, 255, 255));
        Name_Lab_Reg.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Name_Lab_Reg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Name_Lab_Reg.setText("Name :");
        Registration_Panel.add(Name_Lab_Reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 107, 55));

        N_Warn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        N_Warn.setForeground(new java.awt.Color(255, 0, 51));
        N_Warn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registration_Panel.add(N_Warn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 200, 55));

        E_Warn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        E_Warn.setForeground(new java.awt.Color(255, 0, 51));
        E_Warn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registration_Panel.add(E_Warn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 200, 55));

        Ph_Warn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Ph_Warn.setForeground(new java.awt.Color(255, 0, 51));
        Ph_Warn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registration_Panel.add(Ph_Warn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 200, 55));

        Pass_Warn.setBackground(new java.awt.Color(255, 255, 255));
        Pass_Warn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Pass_Warn.setForeground(new java.awt.Color(255, 0, 51));
        Pass_Warn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registration_Panel.add(Pass_Warn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 200, 55));

        Age_Lab_Reg.setBackground(new java.awt.Color(255, 255, 255));
        Age_Lab_Reg.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Age_Lab_Reg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Age_Lab_Reg.setText("Age :");
        Registration_Panel.add(Age_Lab_Reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 107, 55));

        Age_Field.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Age_Field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        Age_Field.setDragEnabled(true);
        Age_Field.setSelectionColor(new java.awt.Color(153, 153, 153));
        Age_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Age_FieldKeyReleased(evt);
            }
        });
        Registration_Panel.add(Age_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 132, 55));

        Gender_Lab_Reg.setBackground(new java.awt.Color(255, 255, 255));
        Gender_Lab_Reg.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Gender_Lab_Reg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Gender_Lab_Reg.setText("Gender :");
        Registration_Panel.add(Gender_Lab_Reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 107, 55));

        Gender_Combo_Reg.setBackground(new java.awt.Color(255, 102, 102));
        Gender_Combo_Reg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Gender_Combo_Reg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "Male", "Female" }));
        Gender_Combo_Reg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        Registration_Panel.add(Gender_Combo_Reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 132, 55));

        Registration_Button.setBackground(new java.awt.Color(255, 255, 255));
        Registration_Button.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        Registration_Button.setText("Save");
        Registration_Button.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        Registration_Button.setContentAreaFilled(false);
        Registration_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registration_ButtonActionPerformed(evt);
            }
        });
        Registration_Panel.add(Registration_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 155, 65));

        Cancel_Button_1.setBackground(new java.awt.Color(255, 255, 255));
        Cancel_Button_1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        Cancel_Button_1.setText("Reset");
        Cancel_Button_1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        Cancel_Button_1.setContentAreaFilled(false);
        Cancel_Button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_Button_1ActionPerformed(evt);
            }
        });
        Registration_Panel.add(Cancel_Button_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 154, 65));

        Age_Warn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Age_Warn.setForeground(new java.awt.Color(255, 0, 51));
        Age_Warn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registration_Panel.add(Age_Warn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 170, 55));

        Back_Button_1.setBackground(new java.awt.Color(255, 255, 255));
        Back_Button_1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        Back_Button_1.setText("Back");
        Back_Button_1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204))));
        Back_Button_1.setContentAreaFilled(false);
        Back_Button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_Button_1ActionPerformed(evt);
            }
        });
        Registration_Panel.add(Back_Button_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 154, 66));

        Register_Lab.setFont(new java.awt.Font("Sitka Text", 3, 48)); // NOI18N
        Register_Lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Register_Lab.setText(".. Registration ..");
        Registration_Panel.add(Register_Lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 880, 91));

        Show_Pass_Check.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Show_Pass_Check.setText("Show Password");
        Show_Pass_Check.setContentAreaFilled(false);
        Show_Pass_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_Pass_CheckActionPerformed(evt);
            }
        });
        Registration_Panel.add(Show_Pass_Check, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 404, 190, 28));

        Registration_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_Pictures/day_bus.gif"))); // NOI18N
        Registration_Panel.add(Registration_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 640, 540));

        Registrion_B_Panel.add(Registration_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 920, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registrion_B_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registrion_B_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void N_Field_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_Field_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N_Field_1ActionPerformed

    private void Ph_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ph_FieldActionPerformed
        // TODO add your handling code here:
        /*
        String size = Ph_Field.getText();
        if(10 == size.length()){
            Ph_Field.setEditable(false);
        }
        */
    }//GEN-LAST:event_Ph_FieldActionPerformed

    private void Registration_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registration_ButtonActionPerformed
        // TODO add your handling code here:
       //call to other frame
       
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/bus_booking_system","root","");
            String reg="insert into registration_form values(?,?,?,?,?,?)";
            PreparedStatement reg_now=con.prepareStatement(reg);
            reg_now.setString(1,N_Field_1.getText());
            reg_now.setString(2,E_Field.getText());
            reg_now.setString(3,Ph_Field.getText());
            reg_now.setString(4,new String(Pass_Field_1.getPassword()));
            reg_now.setString(5,Age_Field.getText());
            String gender = "";
            gender=Gender_Combo_Reg.getSelectedItem().toString();
            reg_now.setString(6, gender);
            reg_now.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted Successfully !");
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       
        if(N_Field_1.getText().trim().isEmpty() && Pass_Field_1.getText().trim().isEmpty() 
                && Ph_Field.getText().trim().isEmpty()){
            N_Warn.setText("!! Enter Name !!");
            Pass_Warn.setText("!! Enter Password !!");
            Ph_Warn.setText("!! Enter Number !!");
        }
        else if(N_Field_1.getText().trim().isEmpty()){
            N_Warn.setText("!! Enter Name !!");
        }
        else if(Pass_Field_1.getText().trim().isEmpty()){
            Pass_Warn.setText("!! Enter Password !!");
        }
        else if(Ph_Field.getText().trim().isEmpty()){
            Ph_Warn.setText("!! Enter Number !!");
        }
        else {
             dispose();
        new Log_In().setVisible(true);
        //setVisible(false);
                
       
        }
   
    }//GEN-LAST:event_Registration_ButtonActionPerformed

    private void Cancel_Button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_Button_1ActionPerformed
        // TODO add your handling code here:
        N_Field_1.setText("");
        E_Field.setText("");
        Ph_Field.setText("");
        Age_Field.setText("");
        Pass_Field_1.setText("");
        Gender_Combo_Reg.setSelectedIndex(0);
       
         //this.setVisible(false);
    }//GEN-LAST:event_Cancel_Button_1ActionPerformed

    private void N_Field_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_N_Field_1KeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,30}$";//Condition
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(N_Field_1.getText());//Input Text Field
        if(!match.matches()){
            N_Warn.setText("!! Invalid Name !!");//Lable for warning
        }
        else
        {
            N_Warn.setText(null);
        }
    }//GEN-LAST:event_N_Field_1KeyReleased

    private void E_FieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_E_FieldKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{1,30}[@][a-z]{0,6}[.][a-z]{0,6}";//Condition
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(E_Field.getText());//Input Text Field
        if(!match.matches()){
            E_Warn.setText("!! Invalid Email !!");//Lable for warning
        }
        else
        {
            E_Warn.setText(null);
        }
    }//GEN-LAST:event_E_FieldKeyReleased

    private void Ph_FieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ph_FieldKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{10,12}$";//Condition
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Ph_Field.getText());//Input Text Field
        if(!match.matches()){
            Ph_Warn.setText("!! Invalid Number !!");//Lable for warning
        }
        else
        {
            Ph_Warn.setText(null);
        }
    }//GEN-LAST:event_Ph_FieldKeyReleased

    private void Age_FieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Age_FieldKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{1,2}$";//Condition
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Age_Field.getText());//Input Text Field
        if(!match.matches()){
            Age_Warn.setText("!! Invalid Age !!");//Lable for warning
        }
        else
        {
            Age_Warn.setText(null);
        }
    }//GEN-LAST:event_Age_FieldKeyReleased

    private void Pass_Field_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pass_Field_1KeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z]{5,10}[0-9]{2,7}[@#$&*_!%^]{1,5}$";//Condition
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Pass_Field_1.getText());//Input Text Field
        if(!match.matches()){
            Pass_Warn.setText("!! Invalid Password !!");//Lable for warning
        }
        else
        {
            Pass_Warn.setText(null);
        }
    }//GEN-LAST:event_Pass_Field_1KeyReleased

    private void Back_Button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_Button_1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Welcom_Form d=new Welcom_Form();
        d.setVisible(true);
    }//GEN-LAST:event_Back_Button_1ActionPerformed

    private void Show_Pass_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_Pass_CheckActionPerformed
        // TODO add your handling code here:
        if (Show_Pass_Check.isSelected()){
            Pass_Field_1.setEchoChar((char)0);
        }
        else {
            Pass_Field_1.setEchoChar('*');
        }
    }//GEN-LAST:event_Show_Pass_CheckActionPerformed

    private void Pass_Field_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Pass_Field_1FocusLost
        // TODO add your handling code here:
        String Pa, Paf;
        Pa=(Pass_Warn.getText());
        if(Pa == "!! Invalid Password !!" ){
            JOptionPane.showMessageDialog(null,"Password should contain Min. 5 alphabets, 2 Numbers, 1 Character respectively !");
        }
        
        uniquePass();
        
    }//GEN-LAST:event_Pass_Field_1FocusLost

    private void N_Field_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_N_Field_1FocusLost
        // TODO add your handling code here:
        
        uniqueName();
        
    }//GEN-LAST:event_N_Field_1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age_Field;
    private javax.swing.JLabel Age_Lab_Reg;
    private javax.swing.JLabel Age_Warn;
    private javax.swing.JButton Back_Button_1;
    private javax.swing.JButton Cancel_Button_1;
    private javax.swing.JTextField E_Field;
    private javax.swing.JLabel E_Warn;
    private javax.swing.JLabel Email_Lab_Reg;
    private javax.swing.JComboBox<String> Gender_Combo_Reg;
    private javax.swing.JLabel Gender_Lab_Reg;
    private javax.swing.JTextField N_Field_1;
    private javax.swing.JLabel N_Warn;
    private javax.swing.JLabel Name_Lab_Reg;
    private javax.swing.JPasswordField Pass_Field_1;
    private javax.swing.JLabel Pass_Lab_Reg;
    private javax.swing.JLabel Pass_Warn;
    private javax.swing.JTextField Ph_Field;
    private javax.swing.JLabel Ph_Warn;
    private javax.swing.JLabel Phone_Lab_Reg;
    private javax.swing.JLabel Register_Lab;
    private javax.swing.JLabel Registration_BG;
    private javax.swing.JButton Registration_Button;
    private javax.swing.JPanel Registration_Panel;
    private javax.swing.JPanel Registrion_B_Panel;
    private javax.swing.JCheckBox Show_Pass_Check;
    // End of variables declaration//GEN-END:variables
}
